name: CI - Validation

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Print Python environment
        run: |
          set -euxo pipefail
          which python3
          python3 -VV
          python3 -m pip --version

      - name: Install package requirements
        run: |
          set -euxo pipefail
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Validate
        run: |
          set -euxo pipefail
          python3 -u OCLP-Plus-GUI.command --validate

      - name: Upload OCLP-Plus logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OCLP-Plus-logs
          path: ~/Library/Logs/Dortania/*.log
          if-no-files-found: ignore
