name: CI - Validation

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
      - name: Install package requirements
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/pip3 install -r requirements.txt
      - name: Validate
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 OCLP-Plus-GUI.command --validate
